const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const targets=document.querySelectorAll('.statement,.collection-card,.chapter-body,.image-break p,.piece-group,.reserved-copy');
targets.forEach(el=>el.classList.add('reveal'));
if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target);}}),{threshold:.1});targets.forEach(el=>io.observe(el));}else{targets.forEach(el=>el.classList.add('visible'));}

const translations={
fr:{nav_collections:'Collections',nav_studio:'Studio',nav_project:'Projet particulier',nav_contact:'Contact',eyebrow:'Studio de design — Belgique',manifesto:'Des formes. Une matière. Une présence.',solid_wood:'Bois massif. Toujours.',silent_presence:'Le mobilier comme<br>présence silencieuse.',discover:'Découvrir les collections',footer_desc:'Mobilier contemporain<br>en bois massif',country:'Belgique',collections_title:'',collections_sub:'<span class="statement-line statement-line-primary">Pièces conçues et fabriquées par Still.</span><span class="statement-line statement-line-secondary">Chaque pièce est unique et se distingue par un numéro de série individuel.</span>',collections_instruction:'Cliquez sur le nom de chaque collection pour la découvrir.',origami_desc:'Angles précis, surfaces tendues, équilibre graphique.',traverse_desc:'Assemblages visibles, lignes franches, construction assumée.',coming:'Créations à venir',epure_desc:'Volumes essentiels, proportions calmes, futures créations.',studio_title:'Concevoir la forme.<br>Façonner la matière.',studio_p1:'STILL imagine et fabrique du mobilier contemporain en bois massif. Chaque pièce naît d’un dialogue entre dessin, proportion, assemblage et lumière.',made_belgium:'Conçu et fabriqué en Belgique.',material_lines:'Une matière vivante,<br>des lignes essentielles.',project_title:'Une pièce pensée<br>pour un lieu précis.',project_p:'Dimensions, essence, finition et usage se rencontrent dans une proposition singulière, développée en dialogue avec chaque espace.',talk_project:'Parler d’un projet',contact_title:'Contact',contact_questions:'Pour toute question',based_brussels:'Basés à Bruxelles.',collection_label:'Collection',acquire:'Acquérir ↗'},
nl:{nav_collections:'Collecties',nav_studio:'Studio',nav_project:'Project op maat',nav_contact:'Contact',eyebrow:'Designstudio — België',manifesto:'Vormen. Een materiaal. Een aanwezigheid.',solid_wood:'Massief hout. Altijd.',silent_presence:'Meubilair als<br>stille aanwezigheid.',discover:'Ontdek de collecties',footer_desc:'Hedendaags meubilair<br>in massief hout',country:'België',collections_title:'',collections_sub:'<span class="statement-line statement-line-primary">Stukken ontworpen en vervaardigd door Still.</span><span class="statement-line statement-line-secondary">Elk stuk is uniek en draagt een individueel serienummer.</span>',collections_instruction:'Klik op de naam van elke collectie om ze te ontdekken.',origami_desc:'Precieze hoeken, gespannen vlakken, grafisch evenwicht.',traverse_desc:'Zichtbare verbindingen, heldere lijnen, uitgesproken constructie.',coming:'Nieuwe creaties binnenkort',epure_desc:'Essentiële volumes, rustige verhoudingen, toekomstige creaties.',studio_title:'De vorm ontwerpen.<br>Het materiaal vormgeven.',studio_p1:'STILL ontwerpt en vervaardigt hedendaags meubilair in massief hout. Elk stuk ontstaat uit een dialoog tussen tekening, verhouding, verbinding en licht.',made_belgium:'Ontworpen en vervaardigd in België.',material_lines:'Een levend materiaal,<br>essentiële lijnen.',project_title:'Een stuk bedacht<br>voor een specifieke plek.',project_p:'Afmetingen, houtsoort, afwerking en gebruik komen samen in een uniek voorstel, ontwikkeld in dialoog met elke ruimte.',talk_project:'Bespreek een project',contact_title:'Contact',contact_questions:'Voor alle vragen',based_brussels:'Gevestigd in Brussel.',collection_label:'Collectie',acquire:'Verwerven ↗'},
en:{nav_collections:'Collections',nav_studio:'Studio',nav_project:'Bespoke project',nav_contact:'Contact',eyebrow:'Design studio — Belgium',manifesto:'Forms. A material. A presence.',solid_wood:'Solid wood. Always.',silent_presence:'Furniture as a<br>silent presence.',discover:'Discover the collections',footer_desc:'Contemporary furniture<br>in solid wood',country:'Belgium',collections_title:'',collections_sub:'<span class="statement-line statement-line-primary">Pieces designed and made by Still.</span><span class="statement-line statement-line-secondary">Each piece is unique and distinguished by an individual serial number.</span>',collections_instruction:'Click the name of each collection to discover it.',origami_desc:'Precise angles, taut surfaces, graphic balance.',traverse_desc:'Visible joints, clear lines, asserted construction.',coming:'New creations coming soon',epure_desc:'Essential volumes, calm proportions, future creations.',studio_title:'Designing the form.<br>Shaping the material.',studio_p1:'STILL designs and makes contemporary furniture in solid wood. Each piece grows from a dialogue between drawing, proportion, joinery and light.',made_belgium:'Designed and made in Belgium.',material_lines:'A living material,<br>essential lines.',project_title:'A piece designed<br>for a specific place.',project_p:'Dimensions, wood species, finish and use come together in a singular proposal, developed in dialogue with each space.',talk_project:'Discuss a project',contact_title:'Contact',contact_questions:'For all enquiries',based_brussels:'Based in Brussels.',collection_label:'Collection',acquire:'Acquire ↗'}};
function setLanguage(lang){const dict=translations[lang]||translations.fr;document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=dict[el.dataset.i18n];if(v)el.innerHTML=v;});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('still-lang',lang);}
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLanguage(b.dataset.lang)));setLanguage(localStorage.getItem('still-lang')||'fr');
